### ISSUE TITLE
Is this charm live? out of date?

### ISSUE THREAD

**Issue by EMCP** [canonical/certbot-charm#13]
Greetings, 

I am an avid charmer, and beginning to charm up a classic Webapp + NGINX + Let'sEncrypt TLS + DNS ... it seems some of what I need could/is solved with certbot and this charm could be useful.. but I tried just now to deploy it as a test and it failed to be found.

Is this charm still good ?  I did see one charm in the hub by some group called yellow but I usually only stick to charms from core teams like Canonical itself.. if I don't hear back maybe I will fork this and just try a local copy.. see if I can help bring this up to date?  I will be testing mostly in AWS but perhaps also need to test in Azure & LXD

```
$ juju deploy certbot
ERROR refresh error: The Charm with the given name was not found in the Store.
$ juju deploy cs:certbot
ERROR cannot resolve URL "cs:certbot": charm or bundle not found
```

**Comment by mhilton** [comment]
Hi @EMCP,

Thanks for your interest, yes this charm is still good, I use it regularly. However there is a bug with the AWS integration where it loses the credentials so is unable to renew properly. I've been meaning to fix that for a while so I'll try and get it sorted soon.

Incidentally the cs:~yellow/certbot version you found is the one we published, but as the charmhub has come online since then I will get it uploaded to there too.

**Comment by mhilton** [comment]
Hi @EMCP,

Thanks for the nudge, you can now find the latest version of this charm in charmhub (https://charmhub.io/certbot).

**Comment by EMCP** [comment]
Can't wait to try it out!  Thanks for responding and publishing
